/* © 2019 Silicon Laboratories Inc. */
#include"nvm_desc.h"
#define static_6_6_app_version 0x0107
#define static_6_6_zw_version 0x040a
const nvm_desc_t static_6_6[] = {
{ "nvmTotalEnd","WORD", 0x0000, 1 },
{ "nvmZWlibrarySize","WORD", 0x0002, 1 },
{ "NVM_INTERNAL_RESERVED_1_far","BYTE", 0x0004, 4 },
{ "EX_NVM_HOME_ID_far","BYTE", 0x0008, HOMEID_LENGTH },
{ "NVM_INTERNAL_RESERVED_2_far","BYTE", 0x000c, 4 },
{ "NVM_HOMEID_far","BYTE", 0x0010, HOMEID_LENGTH },
{ "NVM_NODEID_far","BYTE", 0x0014, 1 },
{ "NVM_CONFIGURATION_VALID_far","BYTE", 0x0015, 1 },
{ "NVM_CONFIGURATION_REALLYVALID_far","BYTE", 0x0016, 1 },
{ "NVM_INTERNAL_RESERVED_3_far","BYTE", 0x0017, 1 },
{ "NVM_PREFERRED_REPEATERS_far","BYTE", 0x0018, MAX_NODEMASK_LENGTH + 3 },
{ "NVM_PENDING_DISCOVERY_far","BYTE", 0x0038, MAX_NODEMASK_LENGTH + 3 },
{ "NVM_RTC_TIMERS_far","BYTE", 0x0058, TOTAL_RTC_TIMER_MAX * RTC_TIMER_SIZE },
{ "EX_NVM_NODE_TABLE_START_far","EX_NVM_NODEINFO", 0x00f8, ZW_MAX_NODES },
{ "EX_NVM_ROUTING_TABLE_START_far","NODE_MASK_TYPE", 0x0580, ZW_MAX_NODES },
{ "EX_NVM_LAST_USED_NODE_ID_START_far","BYTE", 0x1fc8, 1 },
{ "EX_NVM_STATIC_CONTROLLER_NODE_ID_START_far","BYTE", 0x1fc9, 1 },
{ "EX_NVM_PENDING_UPDATE_far","NODE_MASK_TYPE", 0x1fca, 1 },
{ "EX_NVM_SUC_ACTIVE_START_far","BYTE", 0x1fe7, 1 },
{ "EX_NVM_SUC_NODE_LIST_START_far","SUC_UPDATE_ENTRY_STRUCT", 0x1fe8, SUC_MAX_UPDATES },
{ "EX_NVM_SUC_CONTROLLER_LIST_START_far","BYTE", 0x2568, SUC_CONTROLLER_LIST_SIZE },
{ "EX_NVM_SUC_LAST_INDEX_START_far","BYTE", 0x2650, 1 },
{ "EX_NVM_SUC_ROUTING_SLAVE_LIST_START_far","NODE_MASK_TYPE", 0x2651, 1 },
{ "EX_NVM_ZENSOR_TABLE_START_far","NODE_MASK_TYPE", 0x266e, 1 },
{ "EX_NVM_CONTROLLER_CONFIGURATION_far","BYTE", 0x268b, 1 },
{ "EX_NVM_MAX_NODE_ID_far","BYTE", 0x268c, 1 },
{ "EX_NVM_RESERVED_ID_far","BYTE", 0x268d, 1 },
{ "EX_NVM_ROUTECACHE_START_far","ROUTECACHE_LINE", 0x268e, ZW_MAX_NODES },
{ "EX_NVM_ROUTECACHE_NLWR_SR_START_far","ROUTECACHE_LINE", 0x2b16, ZW_MAX_NODES },
{ "EX_NVM_ROUTECACHE_MAGIC_far","BYTE", 0x2f9e, 1 },
{ "EX_NVM_ROUTECACHE_APP_LOCK_far","BYTE", 0x2f9f, MAX_NODEMASK_LENGTH },
{ "nvmZWlibraryDescriptor","t_nvmModuleDescriptor", 0x2fbc, 1 },
{ "nvmApplicationSize","WORD", 0x2fc1, 1 },
{ "EEOFFSET_MAGIC_far","BYTE", 0x2fc3, 1 },
{ "EEOFFSET_CMDCLASS_LEN_far","BYTE", 0x2fc4, 1 },
{ "EEOFFSET_CMDCLASS_far","BYTE", 0x2fc5, APPL_NODEPARM_MAX },
{ "EEOFFSET_WATCHDOG_STARTED_far","BYTE", 0x2fe8, 1 },
{ "nvmApplicationDescriptor","t_nvmModuleDescriptor", 0x2fe9, 1 },
{ "nvmHostApplicationSize","WORD", 0x2fee, 1 },
{ "EEOFFSET_HOST_OFFSET_START_far","BYTE", 0x2ff0, NVM_SERIALAPI_HOST_SIZE },
{ "nvmHostApplicationDescriptor","t_nvmModuleDescriptor", 0x37f0, 1 },
{ "nvmDescriptorSize","WORD", 0x37f5, 1 },
{ "nvmDescriptor","t_NvmModuleSize", 0x37f7, 1 },
{ "nvmDescriptorDescriptor","t_nvmModuleDescriptor", 0x3803, 1 },
{ "nvmModuleSizeEndMarker","WORD", 0x3808, 1 },
};
